; 基本语法元素
(comment) @comment
(string_literal) @string
(integer_literal) @number
(float_literal) @number?
(identifier) @variable

; 关键字（vimscript + vim9）
"vim9script" @keyword
"def" @keyword
"enddef" @keyword
"function" @keyword
"endfunction" @keyword
"var" @keyword
"const" @keyword
"let" @keyword
"unlet" @keyword
"return" @keyword
"if" @keyword
"elseif" @keyword
"else" @keyword
"endif" @keyword
"for" @keyword
"endfor" @keyword
"while" @keyword
"endwhile" @keyword
"try" @keyword
"catch" @keyword
"finally" @keyword
"endtry" @keyword
"autocmd" @keyword
"augroup" @keyword
"command" @keyword
"comclear" @keyword
"delcommand" @keyword
"set" @keyword
"setlocal" @keyword
"source" @keyword
"runtime" @keyword
"execute" @keyword
"colorscheme" @keyword
"silent" @keyword
"map" @keyword
"nmap" @keyword
"vmap" @keyword
"xmap" @keyword
"nnoremap" @keyword
"vnoremap" @keyword
"inoremap" @keyword
"tnoremap" @keyword
"noremap" @keyword

; 括号/分隔符/运算符
"(" @punctuation.bracket
")" @punctuation.bracket
"[" @punctuation.bracket
"]" @punctuation.bracket
"{" @punctuation.bracket
"}" @punctuation.bracket

","  @punctuation.delimiter
"."  @punctuation.delimiter

"->" @operator
"="  @operator
"+=" @operator
"-=" @operator
"*=" @operator
"/=" @operator
"%=" @operator
".=" @operator
"..=" @operator
"==" @operator
"!=" @operator
">"  @operator
"<"  @operator
">=" @operator
"<=" @operator
"=~" @operator
"!~" @operator
"&&" @operator
"||" @operator
